apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vbwet0na8-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vbwet0na8-java-springboot-gitops